# ML_Project 
https://www.kaggle.com/datasets/uciml/forest-cover-type-dataset

# reading data

In [1]:
import pandas as pd

In [2]:
forset_cover=pd.read_csv(r"C:\Users\abdal\Downloads\covtype.csv.zip")
forset_cover

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0            2596      51      3                               258   
1            2590      56      2                               212   
2            2804     139      9                               268   
3            2785     155     18                               242   
4            2595      45      2                               153   
...           ...     ...    ...                               ...   
581007       2396     153     20                                85   
581008       2391     152     19                                67   
581009       2386     159     17                                60   
581010       2384     170     15                                60   
581011       2383     165     13                                60   

        Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                    0                              510   
1                                   -6                              390   
2                                   65                             3180   
3                                  118                             3090   
4                                   -1                              391   
...                                ...                              ...   
581007                              17                              108   
581008                              12                               95   
581009                               7                               90   
581010                               5                               90   
581011                               4                               67   

        Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0                 221             232            148   
1                 220             235            151   
2                 234             238            135   
3                 238             238            122   
4                 220             234            150   
...               ...             ...            ...   
581007            240             237            118   
581008            240             237            119   
581009            236             241            130   
581010            230             245            143   
581011            231             244            141   

        Horizontal_Distance_To_Fire_Points  ...  Soil_Type32  Soil_Type33  \
0                                     6279  ...            0            0   
1                                     6225  ...            0            0   
2                                     6121  ...            0            0   
3                                     6211  ...            0            0   
4                                     6172  ...            0            0   
...                                    ...  ...          ...          ...   
581007                                 837  ...            0            0   
581008                                 845  ...            0            0   
581009                                 854  ...            0            0   
581010                                 864  ...            0            0   
581011                                 875  ...            0            0   

        Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  Soil_Type38  \
0                 0            0            0            0            0   
1                 0            0            0            0            0   
2                 0            0            0            0            0   
3                 0            0            0            0            0   
4                 0            0            0            0            0   
...             ...          ...          ...          ...          ...   
581007            0            0            0            0            0   
581008            0            0            0            0          

In [3]:
forset_cover.head()

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0       2596      51      3                               258   
1       2590      56      2                               212   
2       2804     139      9                               268   
3       2785     155     18                               242   
4       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0            221             232            148   
1            220             235            151   
2            234             238            135   
3            238             238            122   
4            220             234            150   

   Horizontal_Distance_To_Fire_Points  ...  Soil_Type32  Soil_Type33  \
0                                6279  ...            0            0   
1                                6225  ...            0            0   
2                                6121  ...            0            0   
3                                6211  ...            0            0   
4                                6172  ...            0            0   

   Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  Soil_Type38  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type39  Soil_Type40  Cover_Type  
0            0            0           5  
1            0            0           5  
2            0            0           2  
3            0            0           2  
4            0            0           5  

[5 rows x 55 columns]

In [4]:
forset_cover.describe()

Elevation         Aspect          Slope  \
count  581012.000000  581012.000000  581012.000000   
mean     2959.365301     155.656807      14.103704   
std       279.984734     111.913721       7.488242   
min      1859.000000       0.000000       0.000000   
25%      2809.000000      58.000000       9.000000   
50%      2996.000000     127.000000      13.000000   
75%      3163.000000     260.000000      18.000000   
max      3858.000000     360.000000      66.000000   

       Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
count                     581012.000000                   581012.000000   
mean                         269.428217                       46.418855   
std                          212.549356                       58.295232   
min                            0.000000                     -173.000000   
25%                          108.000000                        7.000000   
50%                          218.000000                       30.000000   
75%                          384.000000                       69.000000   
max                         1397.000000                      601.000000   

       Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
count                    581012.000000  581012.000000   581012.000000   
mean                       2350.146611     212.146049      223.318716   
std                        1559.254870      26.769889       19.768697   
min                           0.000000       0.000000        0.000000   
25%                        1106.000000     198.000000      213.000000   
50%                        1997.000000     218.000000      226.000000   
75%                        3328.000000     231.000000      237.000000   
max                        7117.000000     254.000000      254.000000   

       Hillshade_3pm  Horizontal_Distance_To_Fire_Points  ...    Soil_Type32  \
count  581012.000000                       581012.000000  ...  581012.000000   
mean      142.528263                         1980.291226  ...       0.090392   
std        38.274529                         1324.195210  ...       0.286743   
min         0.000000                            0.000000  ...       0.000000   
25%       119.000000                         1024.000000  ...       0.000000   
50%       143.000000                         1710.000000  ...       0.000000   
75%       168.000000                         2550.000000  ...       0.000000   
max       254.000000                         7173.000000  ...       1.000000   

         Soil_Type33    Soil_Type34    Soil_Type35    Soil_Type36  \
count  581012.000000  581012.000000  581012.000000  581012.000000   
mean        0.077716       0.002773       0.003255       0.000205   
std         0.267725       0.052584       0.056957       0.014310   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

         Soil_Type37    Soil_Type38    Soil_Type39    Soil_Type40  \
count  581012.000000  581012.000000  581012.000000  581012.000000   
mean        0.000513       0.026803       0.023762       0.015060   
std         0.022641       0.161508       0.152307       0.121791   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

          Cover_Type  
count  581012.000000  
mean        2.051471  
std         1.396504  
min         1.000000  
25%         1.000000  
50%         2.000000  
75%         2.000000  
max         7.000000  

[8 rows x 55 colu

In [5]:
forset_cover.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581012 entries, 0 to 581011
Data columns (total 55 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Elevation                           581012 non-null  int64
 1   Aspect                              581012 non-null  int64
 2   Slope                               581012 non-null  int64
 3   Horizontal_Distance_To_Hydrology    581012 non-null  int64
 4   Vertical_Distance_To_Hydrology      581012 non-null  int64
 5   Horizontal_Distance_To_Roadways     581012 non-null  int64
 6   Hillshade_9am                       581012 non-null  int64
 7   Hillshade_Noon                      581012 non-null  int64
 8   Hillshade_3pm                       581012 non-null  int64
 9   Horizontal_Distance_To_Fire_Points  581012 non-null  int64
 10  Wilderness_Area1                    581012 non-null  int64
 11  Wilderness_Area2                    581012 non-null 

In [6]:
forset_cover.dtypes

Elevation                             int64
Aspect                                int64
Slope                                 int64
Horizontal_Distance_To_Hydrology      int64
Vertical_Distance_To_Hydrology        int64
Horizontal_Distance_To_Roadways       int64
Hillshade_9am                         int64
Hillshade_Noon                        int64
Hillshade_3pm                         int64
Horizontal_Distance_To_Fire_Points    int64
Wilderness_Area1                      int64
Wilderness_Area2                      int64
Wilderness_Area3                      int64
Wilderness_Area4                      int64
Soil_Type1                            int64
Soil_Type2                            int64
Soil_Type3                            int64
Soil_Type4                            int64
Soil_Type5                            int64
Soil_Type6                            int64
Soil_Type7                            int64
Soil_Type8                            int64
Soil_Type9                      

# 

In [7]:
len(forset_cover.columns)

55

In [8]:
forset_cover.isnull().sum()
# there is no missing value to handle

Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0
Soil_Type11                           0


In [5]:
forset_cover

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0            2596      51      3                               258   
1            2590      56      2                               212   
2            2804     139      9                               268   
3            2785     155     18                               242   
4            2595      45      2                               153   
...           ...     ...    ...                               ...   
581007       2396     153     20                                85   
581008       2391     152     19                                67   
581009       2386     159     17                                60   
581010       2384     170     15                                60   
581011       2383     165     13                                60   

        Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                    0                              510   
1                                   -6                              390   
2                                   65                             3180   
3                                  118                             3090   
4                                   -1                              391   
...                                ...                              ...   
581007                              17                              108   
581008                              12                               95   
581009                               7                               90   
581010                               5                               90   
581011                               4                               67   

        Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0                 221             232            148   
1                 220             235            151   
2                 234             238            135   
3                 238             238            122   
4                 220             234            150   
...               ...             ...            ...   
581007            240             237            118   
581008            240             237            119   
581009            236             241            130   
581010            230             245            143   
581011            231             244            141   

        Horizontal_Distance_To_Fire_Points  ...  Soil_Type32  Soil_Type33  \
0                                     6279  ...            0            0   
1                                     6225  ...            0            0   
2                                     6121  ...            0            0   
3                                     6211  ...            0            0   
4                                     6172  ...            0            0   
...                                    ...  ...          ...          ...   
581007                                 837  ...            0            0   
581008                                 845  ...            0            0   
581009                                 854  ...            0            0   
581010                                 864  ...            0            0   
581011                                 875  ...            0            0   

        Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  Soil_Type38  \
0                 0            0            0            0            0   
1                 0            0            0            0            0   
2                 0            0            0            0            0   
3                 0            0            0            0            0   
4                 0            0            0            0            0   
...             ...          ...          ...          ...          ...   
581007            0            0            0            0            0   
581008            0            0            0            0          

In [9]:
print(forset_cover["Elevation"].min())
print(forset_cover["Elevation"].max())

1859
3858


# Split the data

Here I made both random split and stratified split to compare the perfomance between them but in my running code I implement the stratified split because it's performs better .

# Random Split

In [87]:
# Random Split
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(forset_cover,test_size=0.2,random_state=21)

In [88]:
train_set.shape

(464809, 56)

In [89]:
test_set.shape

(116203, 56)

# Stratified Split

In [10]:

import numpy as np 
forset_cover["Elevation cat"]=pd.cut(forset_cover['Elevation'],
                                     bins=[1800,2050,2300,2550,2800,3050,3300,3550,3800,np.inf],
                                     labels=[1,2,3,4,5,6,7,8,9])

In [11]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=23)


In [12]:
for train_index, test_index in split.split(forset_cover, forset_cover["Elevation cat"]):
    train_set = forset_cover.loc[train_index]
    test_set = forset_cover.loc[test_index]

In [13]:
train_set["Elevation cat"].value_counts() / len(train_set)

Elevation cat
5    0.346809
6    0.338158
4    0.154691
7    0.070328
3    0.057944
2    0.024952
1    0.004660
8    0.002192
9    0.000265
Name: count, dtype: float64

In [14]:
test_set["Elevation cat"].value_counts() / len(test_set)

Elevation cat
5    0.346807
6    0.338158
4    0.154686
7    0.070325
3    0.057942
2    0.024956
1    0.004664
8    0.002194
9    0.000267
Name: count, dtype: float64

# .

In [15]:
forset_cover=train_set.copy()

In [16]:
# Make the correlation
forset_corr=forset_cover
import re
for i in forset_corr.columns:
    pattern=r'^Soil_Type*.'
    if re.match(pattern,i):
         forset_corr.drop(columns=[i],inplace=True)
        
forset_corr.corr()
 # Here I remove any columns that conatins soil type because it's too much and to obvious the correlation between columns.

Elevation    Aspect     Slope  \
Elevation                            1.000000  0.014761 -0.241052   
Aspect                               0.014761  1.000000  0.078671   
Slope                               -0.241052  0.078671  1.000000   
Horizontal_Distance_To_Hydrology     0.305578  0.017584 -0.010366   
Vertical_Distance_To_Hydrology       0.092592  0.070904  0.274923   
Horizontal_Distance_To_Roadways      0.365737  0.024478 -0.215974   
Hillshade_9am                        0.112077 -0.579473 -0.326646   
Hillshade_Noon                       0.204635  0.336499 -0.526370   
Hillshade_3pm                        0.058205  0.647038 -0.176084   
Horizontal_Distance_To_Fire_Points   0.147683 -0.108082 -0.185493   
Wilderness_Area1                     0.132349 -0.139667 -0.234350   
Wilderness_Area2                     0.237863  0.055156 -0.035572   
Wilderness_Area3                     0.066419  0.074329  0.125782   
Wilderness_Area4                    -0.619423  0.083676  0.254009   
Cover_Type                          -0.269917  0.017554  0.147964   
Elevation cat                        0.968555  0.015168 -0.225589   

                                    Horizontal_Distance_To_Hydrology  \
Elevation                                                   0.305578   
Aspect                                                      0.017584   
Slope                                                      -0.010366   
Horizontal_Distance_To_Hydrology                            1.000000   
Vertical_Distance_To_Hydrology                              0.605022   
Horizontal_Distance_To_Roadways                             0.072076   
Hillshade_9am                                              -0.026670   
Hillshade_Noon                                              0.046890   
Hillshade_3pm                                               0.051922   
Horizontal_Distance_To_Fire_Points                          0.051488   
Wilderness_Area1                                           -0.097113   
Wilderness_Area2                                            0.056217   
Wilderness_Area3                                            0.121515   
Wilderness_Area4                                           -0.099803   
Cover_Type                                                 -0.021343   
Elevation cat                                               0.290225   

                                    Vertical_Distance_To_Hydrology  \
Elevation                                                 0.092592   
Aspect                                                    0.070904   
Slope                                                     0.274923   
Horizontal_Distance_To_Hydrology                          0.605022   
Vertical_Distance_To_Hydrology                            1.000000   
Horizontal_Distance_To_Roadways                          -0.046619   
Hillshade_9am                                            -0.166034   
Hillshade_Noon                                           -0.109854   
Hillshade_3pm                                             0.035182   
Horizontal_Distance_To_Fire_Points                       -0.070462   
Wilderness_Area1                                         -0.180888   
Wilderness_Area2                                         -0.008607   
Wilderness_Area3                                          0.146589   
Wilderness_Area4                                          0.078483   
Cover_Type                                                0.080989   
Elevation cat                                             0.088568   

                                    Horizontal_Distance_To_Roadways  \
Elevation                                                  0.365737   
Aspect                                                     0.024478   
Slope                                                     -0.215974   
Horizontal_Distance_To_Hydrology                           0.072076   
Vertical_Distance_To_Hydrology                            -0.046619   
Horizontal_Distance_

# Prepare the Data

In [17]:
# prepare train set
forset_train_prepare=train_set.drop(columns=['Cover_Type'])
target_train=train_set['Cover_Type']

# prepare the test set
forset_test_prepare=test_set.drop(columns=["Cover_Type"])
target_test=test_set["Cover_Type"]



In [104]:
target_train

369994    3
541433    1
176648    2
119495    2
52380     2
         ..
554013    2
410719    1
448811    2
279261    1
149512    1
Name: Cover_Type, Length: 464809, dtype: int64

In [105]:
target_test

533721    2
487832    1
456114    1
156420    2
136445    1
         ..
335806    2
526705    1
559598    2
140818    2
286780    2
Name: Cover_Type, Length: 116203, dtype: int64

In [18]:
# make standardization for train set and test set
from sklearn.preprocessing import StandardScaler
standerd=StandardScaler()
forset_train_prepare_std=forset_train_prepare
forset_train_prepare_std=standerd.fit_transform(forset_train_prepare_std.values)

forset_test_prepare_std=forset_test_prepare
forset_test_prepare_std=standerd.fit_transform(forset_test_prepare_std.values)

In [19]:
forset_train_prepare_std.shape

(464809, 55)

# Build The Models

# Logistic Regression

In [20]:
# Training the model
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(forset_train_prepare_std,target_train)

c:\Users\abdal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
# extract the accuracy
accuracy_lr = log.score(forset_test_prepare_std, target_test)
print("Logistic Regression Accuracy:", accuracy_lr*100)

# Here we can see that the accuracy is too bad 

Logistic Regression Accuracy: 72.49726771253754


In [22]:
# Calculate the Accuracy,Precision,Recall,f1_score,Confusion Matrix

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

predict=log.predict(forset_test_prepare_std)

accuracy =accuracy_score(target_test,predict)

precision=precision_score(target_test,predict,average='weighted')

recall=recall_score(target_test,predict,average='weighted')

f1=f1_score(target_test,predict,average='weighted')

confusion=confusion_matrix(target_test,predict)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.7249726771253754
Precision: 0.7135655622920706
Recall: 0.7249726771253754
F1 Score: 0.7152413047941267
Confusion Matrix:
[[29646 11837     7     0     0    15   869]
 [10258 45299   687     1    42   321    39]
 [    0   730  5872    95     6   519     0]
 [    0     1   265   198     0    70     0]
 [    6  1760    60     0    17    17     0]
 [    0   785  1769    21     6   881     0]
 [ 1745    28     0     0     0     0  2331]]


In [ ]:
# Implement hyperparameter tuning
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100],    
    'penalty': ['l1', 'l2'],                       
    'solver': ['liblinear', 'saga'],                
    'class_weight': [None, 'balanced'],                          
    'tol': [1e-4, 1e-3],                          
}

grid_search = GridSearchCV(log, param_grid, cv=2, n_jobs=-1, verbose=1)

grid_search.fit(forset_train_prepare_std, target_train)

print("Best parameters:", grid_search.best_params_)

# Can't see the result because it takes much time to run 

# Decision Tree Model

In [25]:
# Here I will use the  data without scaling because it's decision tree model

# Train the model
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(forset_train_prepare,target_train)

# Test the model using test set and display the accuracy
accuracy_dtc=dtc.score(forset_test_prepare,target_test)
print("Dections tree Accuracy =",accuracy_dtc*100)

Dections tree Accuracy = 94.02855347968641


In [26]:
from sklearn.model_selection import cross_val_score

scores =cross_val_score(dtc,forset_train_prepare,target_train,scoring='accuracy',cv=10 ) 
print("Scores:", scores*100)
# Here I make cross validation Just to showing the accuracy in defferent division of trainingset

Scores: [93.60168671 93.62104946 93.41666487 93.65332071 93.41021062 93.54790129
 93.42742196 93.41451346 93.64471504 93.57358003]


In [27]:
# Calculate the Accuracy,Precision,Recall,f1_score,Confusion Matrix
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

predict=dtc.predict(forset_test_prepare)

accuracy =accuracy_score(target_test,predict)

precision=precision_score(target_test,predict,average='weighted')

recall=recall_score(target_test,predict,average='weighted')

f1=f1_score(target_test,predict,average='weighted')

confusion=confusion_matrix(target_test,predict)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.940285534796864
Precision: 0.9403315101829925
Recall: 0.940285534796864
F1 Score: 0.9403055251398043
Confusion Matrix:
[[39803  2344     1     0    42     6   178]
 [ 2298 53776   146     0   272   130    25]
 [    1   130  6752    61    15   263     0]
 [    0     1    64   438     0    31     0]
 [   38   234    24     0  1556     8     0]
 [    5   121   249    19    11  3057     0]
 [  192    30     0     0     0     0  3882]]


In [28]:
# Let's make hyperparameter tuning for decision tree classifier 

from sklearn.model_selection import  GridSearchCV

param_grid = {
    'criterion': ['gini', 'entropy'],           
    'splitter': ['best', 'random'],                         
    'max_depth': [3, 5, 10, None],                          
    'min_samples_split': [2, 5, 10],                         
    'min_samples_leaf': [1, 2, 4],                          
    'min_weight_fraction_leaf': [0.0, 0.01, 0.1],          
    'max_features': [None, 'sqrt', 'log2'],                
    
}

grid_search = GridSearchCV(estimator=dtc, param_grid=param_grid, cv=2,scoring='accuracy' ,n_jobs=-1, verbose=1)
grid_search.fit(forset_train_prepare, target_train)
best_params = grid_search.best_params_

print("Best Hyperparameters:", best_params)




Fitting 2 folds for each of 1296 candidates, totalling 2592 fits
Best Hyperparameters: {'criterion': 'entropy', 'max_depth': None, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'splitter': 'best'}


In [29]:
best_params

{'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'splitter': 'best'}

In [30]:
# After hyperparameter tuning train the model again using the best parmeters and look at the new accuracy


from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(**best_params)
dtc.fit(forset_train_prepare,target_train)


accuracy_dtc=dtc.score(forset_test_prepare,target_test)
print("Dections tree Accuracy =",accuracy_dtc*100)

# Here you can see the accuracy increased a little bit

Dections tree Accuracy = 94.45711384387666


In [118]:
# Again after hyperparameter tuning 
# Calculate the Accuracy,Precision,Recall,f1_score,Confusion Matrix

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

predict=dtc.predict(forset_test_prepare)

accuracy =accuracy_score(target_test,predict)

precision=precision_score(target_test,predict,average='weighted')

recall=recall_score(target_test,predict,average='weighted')

f1=f1_score(target_test,predict,average='weighted')

confusion=confusion_matrix(target_test,predict)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.9443732089532972
Precision: 0.9443575270974955
Recall: 0.9443732089532972
F1 Score: 0.9443599337130208
Confusion Matrix:
[[40030  2136     0     0    28     8   172]
 [ 2188 53961   137     0   231   109    21]
 [    1   127  6781    51    12   250     0]
 [    0     0    80   429     0    25     0]
 [   40   230    15     0  1570     5     0]
 [    9   102   245    19    11  3076     0]
 [  180    31     0     0     1     0  3892]]


# SVM Model

In [ ]:
from sklearn.svm import SVC

svc=SVC()

svc.fit(forset_train_prepare_std,target_train)

accuracy_svc=svc.score(forset_test_prepare_std,target_test)
print("The accuracy = ",accuracy_svc)

# it takes much time to run

# KNN modle

In [31]:
# training and testing the model
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier()
knn.fit(forset_train_prepare_std,target_train)

accuracy=knn.score(forset_test_prepare_std,target_test)
print("the accuracy = ",accuracy*100)



the accuracy =  92.99329621438345


In [32]:
# Calculate the Accuracy,Precision,Recall,f1_score,Confusion Matrix

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

predict=knn.predict(forset_test_prepare_std)

accuracy =accuracy_score(target_test,predict)

precision=precision_score(target_test,predict,average='weighted')

recall=recall_score(target_test,predict,average='weighted')

f1=f1_score(target_test,predict,average='weighted')

confusion=confusion_matrix(target_test,predict)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.9299329621438345
Precision: 0.9296912547157893
Recall: 0.9299329621438345
F1 Score: 0.9297556730032793
Confusion Matrix:
[[39423  2717     7     0    24     6   197]
 [ 2459 53591   177     1   218   165    36]
 [    4   214  6570    51     7   376     0]
 [    0     1   106   400     0    27     0]
 [   61   328    29     0  1430    12     0]
 [   14   194   430    25    10  2789     0]
 [  217    29     0     0     0     0  3858]]


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score
from scipy.stats import randint, uniform
param_dist = {
    'n_neighbors': randint(1, 30),               
    'weights': ['uniform', 'distance'],       
    'metric': ['euclidean', 'manhattan', 'minkowski'], 
    'p': randint(1, 5),                         
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'], 
    'leaf_size': randint(20, 50),               
    'n_jobs': [-1]                            
}

random_search = RandomizedSearchCV(knn, param_distributions=param_dist, n_iter=100, cv=5,
                                   scoring='accuracy', n_jobs=-1, verbose=1, random_state=42)
random_search.fit(forset_train_prepare_std, target_train)
best_params = random_search.best_params_
print("Best Hyperparameters:", best_params)

# I spent 376min without getting any result 